# Generated by Django 5.1 on 2024-08-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
    ]
