# Generated by Django 5.1 on 2024-08-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0002_rename_customer_email_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
