# Generated by Django 5.1 on 2024-08-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0004_alter_order_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='name',
        ),
    ]
