# Generated by Django 5.1 on 2024-08-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0005_rename_supplier_email_supplier_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='sales_date',
            new_name='transaction_date',
        ),
    ]
