# Generated by Django 5.1 on 2024-08-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0006_rename_sales_date_inventory_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_quantity',
            new_name='quantity_in_stock',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sale_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InventorySystem.product'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventorySystem.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventorySystem.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventorySystem.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
