# Generated by Django 5.0.7 on 2024-08-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0009_inventory_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InventorySystem.product'),
        ),
    ]
