# Generated by Django 5.1 on 2024-08-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0011_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='inventory',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('KHALTI', 'KHALTI'), ('ESewa', 'ESewa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='InventorySystem.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
